language: python
python:
  - "3.6"
before_install:
    - apt-get install rabbitmq-server
install: true
#  - pip install -e . --use-mirrors
before_script:
  - pip install -r install/requirements.txt --use-mirrors
  - git clone https://github.com/akayunov/amqpsfw.git
  - cd amqpsfw/sfw
#  - git checkout -qf 17b8119796516195527dcb4f454a2ebd41d60244
script:
  - pytest test/
after_success: true
after_failure: true