language: python
python:
  - "3.6"
before_install: true
install: true
#  - pip install -e . --use-mirrors
before_script:
  - git clone https://github.com/akayunov/amqpsfw.git
  - cd amqpsfw
  - ../venv/bin/pip install -r install/requirements.txt
#  - git checkout -qf 17b8119796516195527dcb4f454a2ebd41d60244
script:
  - pytest test/
after_success: true
after_failure: true